name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Neovim
        uses: MunifTanjim/setup-neovim-action@v1
      
      - name: Verify Neovim install 
        run: nvim --version

      - name: Run tests
        run: |
          XDG_CONFIG_HOME=$(pwd)/tests nvim --headless -l -c 'PlenaryBustedDirectory tests'
